# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='CreateTime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_time',
            field=models.DateTimeField(null=True, verbose_name='\u6587\u7ae0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(default='Title', max_length=32, verbose_name='\u6587\u7ae0\u6807\u9898'),
        ),
    ]
